files:
  - source: /_pages/en_US/*.txt
    ignore:
      - /_pages/en_US/Recent-Community-Events.txt
    translation: /_pages/%locale_with_underscore%/%original_file_name%
  - source: /_data/navigation/en_US.yml
    translation: /_data/navigation/%locale_with_underscore%.yml
